-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  points int default 0,
  role text default 'user'
);

-- Create menu_items table
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  category text,
  image text
);

-- Create rewards table
create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  title text not null,
  cost int not null,
  icon text
);

-- Create transactions table
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  total numeric,
  points_earned int,
  items jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.rewards enable row level security;
alter table public.transactions enable row level security;

-- Create Policies
-- Profiles: Viewable by everyone (or just owner?), Editable by owner
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

-- Menu Items: Viewable by everyone, Editable by admins (skip admin check for now, just read-only for public)
create policy "Menu items are viewable by everyone" on public.menu_items for select using (true);

-- Rewards: Viewable by everyone
create policy "Rewards are viewable by everyone" on public.rewards for select using (true);

-- Transactions: Viewable and insertable by owner
create policy "Users can view own transactions" on public.transactions for select using (auth.uid() = user_id);
create policy "Users can insert own transactions" on public.transactions for insert with check (auth.uid() = user_id);

-- Function to handle new user signup (optional, but good practice)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
